### ISSUE TITLE
looking for a release to install

### ISSUE THREAD

**Issue by splaisan** [alekseyzimin/JASPER_release#2]
Hi
I was sent here from https://github.com/alguoo314/JASPER_integrated_release to get a JASPER release that would install with jellyfish
Can you please help me to the required tar
thanks

**Comment by splaisan** [comment]
I meanwhile managed to build jellyfish from source and define PYTHONPATH to see it from Jasper.sh

**Comment by alekseyzimin** [comment]
Hello, you can use the v1.0.4 release version from here:
https://github.com/alekseyzimin/JASPER_release/releases

**Comment by splaisan** [comment]
thanks a lot, I finally made it to install
